source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Sonicam' do
pod 'ReactiveCocoa', '~> 7.0'
pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage', '~> 4.0'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'SnapKit', '~> 4.0.0'
end
